version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass suckmycock
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - redis-data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 69.69.0.1
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      node_net:
        ipv4_address: 69.69.0.2
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 69.69.0.0/16
volumes:
  redis-data:
