version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      node_net:
        ipv4_address: 69.69.0.69
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 69.69.0.0/16
volumes:
  redis-data:
